default_agent: bond
agents:
  bond:
    name: bond
    entrypoint: /home/tobe/Src/MadeTech/GDS/terraform-skeleton/src/strands/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /home/tobe/Src/MadeTech/GDS/terraform-skeleton/src/strands
    aws:
      execution_role: null
      execution_role_auto_create: true
      account: '261219435789'
      region: eu-west-2
      ecr_repository: null
      ecr_auto_create: true
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: bond-sR13kFEucG
      agent_arn: arn:aws:bedrock-agentcore:eu-west-1:261219435789:runtime/bond-sR13kFEucG
      agent_session_id: 773e2b61-3072-4789-b224-4f96f072e65c
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_AND_LTM
      memory_id: Bond_mem-iAXDaCEtc7
      memory_arn: null
      memory_name: bond_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
