default_agent: Bond
agents:
  Bond:
    name: Bond
    entrypoint: /home/tobe/Src/MadeTech/GDS/terraform-skeleton/src/strands/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /home/tobe/Src/MadeTech/GDS/terraform-skeleton/src/strands
    aws:
      execution_role: arn:aws:iam::261219435789:role/AmazonBedrockAgentCoreSDKRuntime-eu-west-2-8f8fd9ecdd
      execution_role_auto_create: false
      account: '261219435789'
      region: eu-west-2
      ecr_repository: 261219435789.dkr.ecr.eu-west-2.amazonaws.com/bedrock-agentcore-bond
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-bond-builder
      execution_role: arn:aws:iam::261219435789:role/AmazonBedrockAgentCoreSDKCodeBuild-eu-west-2-8f8fd9ecdd
      source_bucket: bedrock-agentcore-codebuild-sources-261219435789-eu-west-2
    memory:
      mode: STM_ONLY
      memory_id: Bond_mem-iAXDaCEtc7
      memory_arn: arn:aws:bedrock-agentcore:eu-west-2:261219435789:memory/Bond_mem-iAXDaCEtc7
      memory_name: Bond_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
