default_agent: main
agents:
  main:
    name: main
    entrypoint: /home/tobe/Src/MadeTech/GDS/terraform-skeleton/src/strands/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /home/tobe/Src/MadeTech/GDS/terraform-skeleton/src/strands
    aws:
      execution_role: arn:aws:iam::261219435789:role/AmazonBedrockAgentCoreSDKRuntime-eu-west-1-0d6e4079e3
      execution_role_auto_create: false
      account: '261219435789'
      region: eu-west-1
      ecr_repository: 261219435789.dkr.ecr.eu-west-1.amazonaws.com/bedrock-agentcore-main
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: main-5sSRD59VCu
      agent_arn: arn:aws:bedrock-agentcore:eu-west-1:261219435789:runtime/main-5sSRD59VCu
      agent_session_id: 17c7dde5-a1eb-4758-a113-8673a9bc4a19
    codebuild:
      project_name: bedrock-agentcore-main-builder
      execution_role: arn:aws:iam::261219435789:role/AmazonBedrockAgentCoreSDKCodeBuild-eu-west-1-0d6e4079e3
      source_bucket: bedrock-agentcore-codebuild-sources-261219435789-eu-west-1
    memory:
      mode: STM_ONLY
      memory_id: main_mem-fPLHyaB57t
      memory_arn: arn:aws:bedrock-agentcore:eu-west-1:261219435789:memory/main_mem-fPLHyaB57t
      memory_name: main_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
