---
title: "How we evaluated AI agents for making eligibility judgements"
date: 10 June 2026
date-format: "MMMM YYYY"
format:
    revealjs:
        reference-location: document
        html-math-method: katex # need this for the calligraphic N in the normal distribution
        theme: [styles.scss, night]
        transition: none
        center: true
        background-transition: none
        incremental: false
        smaller: false
        self-contained: true
        slide-number: true
        toc: true
---

# Background

- GDS have an ambition to leverage Agentic technology to help UK residents understand what they are eligible for from government
- Eligibility rules can be complex, vague and/or incomplete
- Agentic innovations present an opportunity to offer bespoke, person-centric advice which abstracts away the cognitive load of understanding how their personal situation fits into a complex ecosystem
    - A known issue surfaced through user research with advisors is that there are often so many edge case circumstances, that in total a non-trivial fraction of the population falls into one or more edge cases

---

# Technical Challenges

- Model hallucination
- Epistemic Limits; having an agent answer "I don't know"
- Testing output space when input space effectively unbounded

---

# Domain Challenges

- Importance of giving the best possible answers
- We are not subject matter experts on any particular benefit
- We don't have a sufficiently large/stratified cohort of users to be able to draw any empirically sound conclusions
    - We therefore had to lean on automated testing approaches

---

# Questions we sought to answer

* To what extent is an agent able to report `INDETERMINATE` when presented with a situation not explicitly covered by eligibility rules
* What representation of eligibility rules results in best performance (i.e. accuracy, consistency, token use, latency)
* How can we control for systematic errors relating to methodology

---

# How we went about answering them

*

---

# Four approaches

* Two modes of eligibility rules representation:
  1. "Free text" - rules in a human readable format taken from gov.uk website
  2. "Structured" - converting rules into a graphical format, exposed to the agent via MCP tools

* Two modes of exposing scenario to agent-under-test:
  1. "Actor" - another agent was provided with the test scenario, and told to converse with the agent-under-test, pretending to be a human in the situation described by the scenario
  2. "Facts bundle" - Scenario was provided to the agent-under-test directly

---

|                  | Actor                        | Facts Bundle                       |
|------------------|------------------------------|------------------------------------|
| Free Text        | Free Text with Actor         | Free Text with Facts Bundle        |
| Structured Rules | Structured Rules with Actor  | Structured Rules with Facts Bundle |

: Combinatorial evaluation of above modes

---

# Method: Data synthesis with ground truth

---

# Method: Agentic test harness

---

# Results: Comparison of the four approaches

---

# Results: Preferential failure modes

---

# Results: MoE

---
