from mcp_server.models.eligibility_check_models import Implications

def check_universal_credit_eligibility_implications() -> Implications:
    return Implications() \
        .add("Housing Benefit", "If you're eligible for Universal Credit, you cannot claim Housing Benefit. Universal Credit includes help with housing costs instead. If you're currently receiving Housing Benefit, it will stop when you claim Universal Credit.") \
        .add("Income Support", "Universal Credit replaces Income Support. If you're currently receiving Income Support, you cannot receive both at the same time. You would need to move to Universal Credit.") \
        .add("Income-based Jobseeker's Allowance (JSA)", "Universal Credit replaces income-based Jobseeker's Allowance. If you're currently receiving income-based JSA, you cannot receive both at the same time. You would need to move to Universal Credit.") \
        .add("Income-related Employment and Support Allowance (ESA)", "Universal Credit replaces income-related Employment and Support Allowance. If you're currently receiving income-related ESA, you cannot receive both at the same time. You would need to move to Universal Credit.") \
        .add("Working Tax Credit", "Universal Credit replaces Working Tax Credit. If you're currently receiving Working Tax Credit, you cannot receive both at the same time. You would need to move to Universal Credit.") \
        .add("Child Tax Credit", "Universal Credit replaces Child Tax Credit. If you're currently receiving Child Tax Credit, you cannot receive both at the same time. Universal Credit includes support for children instead.") \
        .add("Pension Credit", "If you or your partner are receiving Pension Credit and one of you is under State Pension age, claiming Universal Credit will stop your Pension Credit payments. You're usually better off staying on Pension Credit. Check with a benefits calculator before applying.") \
        .add("Council Tax Reduction", "If you're eligible for Universal Credit, you may also be eligible for Council Tax Reduction (also called Council Tax Support). This is a separate benefit administered by your local council that can help reduce your council tax bill. You need to apply separately to your local council.") \
        .add("Free School Meals", "If you're eligible for Universal Credit and have children, they may be eligible for free school meals if your household income (after tax and not including any benefits) is less than £7,400 per year.") \
        .add("Healthy Start Vouchers", "If you're eligible for Universal Credit and are pregnant or have children under 4, you may be eligible for Healthy Start vouchers to help buy healthy food and milk. Your household income must be £408 or less per month after tax, not including any benefits.") \
        .add("Sure Start Maternity Grant", "If you're eligible for Universal Credit and expecting your first child or expecting a multiple birth, you may be eligible for a Sure Start Maternity Grant of £500 to help with the costs of a new baby.") \
        .add("Budgeting Advances", "If you're eligible for Universal Credit and have been receiving it for at least 6 months, you may be able to get a Budgeting Advance - an interest-free loan to help with emergency household costs or getting a job.") \
        .add("NHS Low Income Scheme", "If you're eligible for Universal Credit, you may qualify for help with health costs through the NHS Low Income Scheme, including free prescriptions, dental treatment, eye tests, and travel to hospital for NHS treatment.") \
        .add("Carer's Allowance", "If you're eligible for Universal Credit and caring for someone for at least 35 hours a week, you may also be eligible for Carer's Allowance. However, if you receive Carer's Allowance, it will be taken into account as income when calculating your Universal Credit payment.")
